AWSTemplateFormatVersion: '2010-09-09'
Description: Create S3 bucket

Parameters:
  BucketName:
    Type: String
    Description: rambucketdevops5

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
